### ISSUE TITLE
httpfox.gay returning cloudflare 502 bad gateway

### ISSUE THREAD

**Issue by Juliasmatius** [ItsJamie9494/http.fox#11]
The site is currently responding with http 502 from cloudflare

![image](https://github.com/user-attachments/assets/a23ca640-f002-403b-b607-451b8f924a4f)

**Comment by ItsJamie9494** [comment]
yeah, unfortunately the person who was hosting the site on my behalf stopped hosting it, and I haven't had the time to get it back up yet. apologies.

**Comment by Juliasmatius** [comment]
You could set up github or cloudflare pages on the domain

**Comment by ItsJamie9494** [comment]
should be back up again

**Comment by Juliasmatius** [comment]
nope, its not...

**Comment by ItsJamie9494** [comment]
working on it now

**Comment by ItsJamie9494** [comment]
mind trying again?

**Comment by Juliasmatius** [comment]
Seems to work now.
